config/routes.rb
LcboApp::Application.routes.draw do
  root to: "products#index"
  post "products" => "products#index", :as => "list_products"

  resources :products, :only => [:index, :show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  CATEGORIES = %w()

  def formatted_price(price_in_cents)
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end

  helper_method :formatted_price

end

app/controllers/products_controller.rb
require 'lcbo_api'
require 'open-uri'

class ProductsController < ApplicationController
  
  def index
    @start_page = params[:start_page]
    @end_page = params[:end_page]
    @products = API.get_pages(@start_page, @end_page)
  end

  def show
    id = params[:id]
    products_json = open('http://lcboapi.com/products').read
    products = JSON.parse(products_json)
    products['result'].each do |product|
      @product = product if product['id'].to_i == id.to_i
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def total_pages
    products_json = open("http://lcboapi.com/products").read
    page = JSON.parse(products_json)
    page['pager']['final_page']
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/backup_index.html.erb
<% @all_products.each do |index| %>
  <% index['result'].each do |product| %>
    <section>
      <%= link_to product['name'], product_path(product['id']) %>
      <span><%= product['price_per_liter_of_alcohol_in_cents'].to_f / 100 %> </span>
    </section>
  <% end %>
<% end %>

app/views/products/index.html.erb
<h1>Dionysus-by-the-Dime</h1>

<p>There are <%= total_pages %> pages.</p>
<p>Which pages would you like to display?</p>

<div class="form-wrapper">
  <%= form_tag list_products_path do %>
  <%= label_tag(:start_page, "Start page:") %>
  <%= text_field_tag (:start_page) %>
  <%= label_tag(:end_page, "End page:") %>
  <%= text_field_tag (:end_page) %>
  <%= submit_tag("Display") %>
  <% end %>
</div>  

<% if @start_page != nil && @end_page != nil %>
  <p>Now displaying pages <%= @start_page %> to <%= @end_page %></p>
  <% categories = Array.new %>
    
  <% @products.each do |page| %>
     <% page['result'].each do |product| %>
        <% categories << product['primary_category'] %>
        <% categories.uniq! %>
    <% end %>
  <% end %>
  <%= categories %>
<% else %>
  <p>Please select start and end pages.</p>
<% end %>
  
  

app/views/products/show.html.erb
<h3><%= @product['name'] %></h3> 
<%= formatted_price @product['price_in_cents'] %>
<br>
<div>
<img src="<%= @product['image_thumb_url'] %>" alt="">
</div>
<%= link_to "Home", products_path %>